### ISSUE TITLE
Teensy4.1 and DM332T Drivers for a Basic CNC Machine

### ISSUE THREAD

**Issue by silver2row** [grblHAL/iMXRT1062#89]
Hello...I have three drivers, three axes, and a standalone DC Motor for a spindle.

For some reason with these DM332T drivers, I cannot make motor movement. I have posted on here before this time looking for advice.

I just downloaded the newer firmware and I will be installing it soon. Anyway...

The drivers have this pin called `OPTO`. It needs 5v supplied to it. What pins from the `T41U5XBB` board with the teensy4.1 would I use to supply the 5v? Are there any pin mappings stating 5v output even with my 12v PSU?

Seth

P.S. Thank you in advance if you can make me understand.

**Comment by terjeio** [comment]
You need to add level translators to the pins since the MCU is a 3.3V device. The [T41U5XBB](https://github.com/phil-barrett/grblHAL-teensy-4.x/blob/master/schematic%202%20of%202.png) board uses 74 series chips, you may also use [resistors and transistors](https://github.com/terjeio/CNC_Boosterpack#bonus-design-polulu-style-motor-driver-dummy).
